### ISSUE TITLE
Unifi OS 4. (EA) changed Cookie name

### ISSUE THREAD

**Issue by jasperslits** [AngellusMortis/pyunifiprotect#382] opened 2024-05-03 07:48 UTC
In case others are running into this.

Unifi OS 4.x is released in Early Access (EA). I noticed it breaks both Protect and Unifi network due to the missing expected cookie and this is due to the Cookie name change from TOKEN to UOS_TOKEN. 

This requires a change in api.py so I am happy to create a PR for it but just wondering if the cookie logic cant be simplified as there's only one cookie set by Protect / Unifi OS. That's used for Unifi Network and worked well.

**Comment by AngellusMortis** [comment] 2024-05-03 10:36
Nothing can really be simplify since UniFi Network and UniFi Protect are completely different. pyunifiprotect and aiounifi are completely designed differently and not compatible with each other at all.

I considered at one point abstraction a lot of code out of pyunifiprotect and making a UniFi OS or UniFi Connect package, but with how Ubiquiti treats the community, I do not have much interest anymore.

**Comment by Nixon506E** [comment] 2024-05-06 16:41
@jasperslits Any update on the auth fix for 4.x? I see that aiounifi just passed the cookie headers through the websocket and things worked

**Comment by AngellusMortis** [comment] 2024-05-06 16:46
Do not ask for updates on issues. EA is not officially supported and myself and the other maintainers have no way to install EA UniFi OS versions. Contributors will make a PR when they have the time to/want to. Otherwise, you are free to make a PR yourself.

**Comment by jonbloom** [comment] 2024-05-09 22:04
I’d happily donate a UniFi console (CK+) to dedicate to EA for any maintainer interested — I assume “no way to install EA versions” is due to lack of dedicated testing hardware, otherwise it’s must be a self-imposed restriction as the rest of those asking about it are able to install any release branch they like. Thanks!

**Comment by AngellusMortis** [comment] 2024-05-09 22:09
Having a console is only part of the picture. I have an extra console. I think Nick does too. The problem is having the ecosystem set up. Testing updates means you need Protect running. With a drive. With multiple varying types of cameras.

Essentialy you need a whole working Protect install. Yes, _in this case_ you would likely not need more then a single Protect instance with no cameras running. But if you look back at some of the previous issues from EA, that was not always the case. In fact, one of them (the UUID one) only happened _if you had remote access disabled_.

**Comment by jasperslits** [comment] 2024-05-10 07:35
I understand the challenge but if Ubiquiti releases Unifi OS 4 as GA (assuming they skip Release Candidate) today then everyone immediately upgrades their console and tickets are created in HA as Protect doesn't work anymore. As it's then GA, the whole 'EA is not supported' disclaimer doesn't apply anymore. You'd want to have support added ideally in HA ahead of new releases because it's not immediately obvious for most users that they need to wait for next release. 

Prior upgrades to Unifi OS 2.x -> 3.0 -> 3.2 didn't change to my best knowledge the authentication piece so it came a bit as a surprise to see the cookie name changed.

**Comment by AngellusMortis** [comment] 2024-05-10 12:28
Then I guess you better get to making that PR you said multiple times you were going to make.

**Comment by jasperslits** [comment] 2024-05-10 13:28
There's no need for such a snarky comment, I am just trying to help. Two days ago I added a comment to PR #383 "
I am about to create a proper PR for Unifi OS 4 support but looking for a bit of guidance on what works best:

* I pull current main (5.2.0) from pyunifiprotect
* I base my changes on it
*.I submit a PR
Beause current HA - which I used - doesn't have the PTZ and other changes from 5.2.0 so it ends up with deletes. Happy to follow your guidance as I dont want to create unnecessary work when it comes to reviewing or merging the PR."

**Comment by jasperslits** [comment] 2024-05-10 19:30
The problem is that if I use the CLI with 5.2.0 as-is to test it, like "unifi-protect cameras 61684d1203053d038700088d save-snapshot /tmp/foo.png", it works without authentication errors and without any changes. Likewise with other commands like "nvr" work. No authentication errors but it behaves different from HA. 

So I can make the changes in api.py against main / 5.2.0 but there's no way to test it when used within HA due to that pedantic v1 problem. As the related PR for HA Core was already closed, hence I used the shipped version.  

In the other PR I linked to a commit I already created with the required changes api.py, so I did that work and tested it. And I can rebase it on main so it keeps the PTZ stuff in.  

I appreciate the work you're putting into it and my other comment on GA was more to acknowledge that it's not easy to deal with undocumented API changes from Ubiquiti and their GA / RC / EA stuff which has no predictable timeline or roadmap. Apologies if that came over as complaining. 
It's just that I have Unifi OS 4 on my console already and happy to help with the relevant changes given your comments on time it takes for new updates / upgrades.

**Comment by jasperslits** [comment] 2024-05-13 07:10
Can be closed as there's PR #388 with the code changes.

**Comment by AngellusMortis** [comment] 2024-05-13 12:14
Issues are not closed until PRs are merged.

**Closed** 2024-05-16 16:12 UTC

**Comment by Nixon506E** [comment] 2024-05-17 13:40
I’m afraid to ask but am wondering if we should expect a release with this fix soon?
